name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run containers
      run: docker compose -f "docker-compose-ci.yml" up -d --build
    - name: Install dependencies
      run: |
        sleep 30
        docker ps -a
        docker logs watchdog
        python -m pip install --upgrade pip
        pip install -e '.[testing]'
    - name: Test with pytest
      run: |
        pytest --cov-fail-under=100 --cov=src/datajunction -vv tests/ --doctest-modules src/datajunction --with-integration --with-slow-integration
